version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    reviewers:
      - "AxonIQ/inspector-axon"
    groups:
      github-dependencies:
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    reviewers:
      - "AxonIQ/inspector-axon"
    groups:
      maven-dependencies:
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    reviewers:
      - "AxonIQ/inspector-axon"
    groups:
      npm-dependencies:
        update-types:
          - "patch"
          - "minor"
          - "major"