GET http://localhost:8080/send/commands/aggregate?count=99&delay=1&worktime=1
Tenant-Id: tenant-one

###

GET http://localhost:8080/send/commands/aggregate?count=99&delay=1&worktime=1
Tenant-Id: tenant-two

###

GET http://localhost:8080/send/commands/new-aggregate?count=1&delay=1&worktime=100
Tenant-Id: tenant-three

###

GET http://localhost:8080/send/query/subscription?count=1&delay=1&worktime=100
Tenant-Id: tenant-one

###

GET http://localhost:8080/send/query?count=1&delay=100
Tenant-Id: tenant-two

####

GET http://localhost:8080/send/query?count=90&delay=100
Tenant-Id: tenant-one

###




