;
CREATE USER IF NOT EXISTS "SA" SALT '4ebb585a10373988' HASH '39a4dfa89574866f177d898b9f7c4749c526efc4ae92df425e000470068ff594' ADMIN;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "PUBLIC"."ASSOCIATION_VALUE_ENTRY"(
    "ID" BIGINT NOT NULL,
    "ASSOCIATION_KEY" VARCHAR(255) NOT NULL,
    "ASSOCIATION_VALUE" VARCHAR(255),
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "SAGA_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ASSOCIATION_VALUE_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION_VALUE_ENTRY;
CREATE INDEX "PUBLIC"."IDXK45EQNXKGD8HPDN6XIXN8SGFT" ON "PUBLIC"."ASSOCIATION_VALUE_ENTRY"("SAGA_TYPE", "ASSOCIATION_KEY", "ASSOCIATION_VALUE");
CREATE INDEX "PUBLIC"."IDXGV5K1V2MH6FRXUY5C0HGBAU94" ON "PUBLIC"."ASSOCIATION_VALUE_ENTRY"("SAGA_ID", "SAGA_TYPE");
CREATE MEMORY TABLE "PUBLIC"."DEAD_LETTER_ENTRY"(
    "DEAD_LETTER_ID" VARCHAR(255) NOT NULL,
    "CAUSE_MESSAGE" VARCHAR(255),
    "CAUSE_TYPE" VARCHAR(255),
    "DIAGNOSTICS" BLOB,
    "ENQUEUED_AT" TIMESTAMP NOT NULL,
    "INDEX" BIGINT NOT NULL,
    "LAST_TOUCHED" TIMESTAMP,
    "AGGREGATE_IDENTIFIER" VARCHAR(255),
    "EVENT_IDENTIFIER" VARCHAR(255) NOT NULL,
    "MESSAGE_TYPE" VARCHAR(255) NOT NULL,
    "META_DATA" BLOB,
    "PAYLOAD" BLOB NOT NULL,
    "PAYLOAD_REVISION" VARCHAR(255),
    "PAYLOAD_TYPE" VARCHAR(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT,
    "TIME_STAMP" VARCHAR(255) NOT NULL,
    "TOKEN" BLOB,
    "TOKEN_TYPE" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "PROCESSING_GROUP" VARCHAR(255) NOT NULL,
    "PROCESSING_STARTED" TIMESTAMP,
    "SEQUENCE_IDENTIFIER" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."DEAD_LETTER_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("DEAD_LETTER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEAD_LETTER_ENTRY;
CREATE INDEX "PUBLIC"."IDXE67WCX5FIQ9HL4Y4QKHLCJ9CG" ON "PUBLIC"."DEAD_LETTER_ENTRY"("PROCESSING_GROUP");
CREATE INDEX "PUBLIC"."IDXRWUCPGS6SN93LDGOEH2Q9K6BN" ON "PUBLIC"."DEAD_LETTER_ENTRY"("PROCESSING_GROUP", "SEQUENCE_IDENTIFIER");
CREATE MEMORY TABLE "PUBLIC"."DOMAIN_EVENT_ENTRY"(
    "GLOBAL_INDEX" BIGINT NOT NULL,
    "EVENT_IDENTIFIER" VARCHAR(255) NOT NULL,
    "META_DATA" BLOB,
    "PAYLOAD" BLOB NOT NULL,
    "PAYLOAD_REVISION" VARCHAR(255),
    "PAYLOAD_TYPE" VARCHAR(255) NOT NULL,
    "TIME_STAMP" VARCHAR(255) NOT NULL,
    "AGGREGATE_IDENTIFIER" VARCHAR(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."DOMAIN_EVENT_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("GLOBAL_INDEX");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOMAIN_EVENT_ENTRY;
CREATE MEMORY TABLE "PUBLIC"."GIFT_CARD_ENTITY"(
    "ID" VARCHAR(255) NOT NULL,
    "INITIAL_VALUE" INTEGER,
    "REMAINING_VALUE" INTEGER
);
ALTER TABLE "PUBLIC"."GIFT_CARD_ENTITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GIFT_CARD_ENTITY;
CREATE MEMORY TABLE "PUBLIC"."SAGA_ENTRY"(
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "REVISION" VARCHAR(255),
    "SAGA_TYPE" VARCHAR(255),
    "SERIALIZED_SAGA" BLOB
);
ALTER TABLE "PUBLIC"."SAGA_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BD" PRIMARY KEY("SAGA_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_ENTRY;
CREATE MEMORY TABLE "PUBLIC"."SNAPSHOT_EVENT_ENTRY"(
    "AGGREGATE_IDENTIFIER" VARCHAR(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" VARCHAR(255) NOT NULL,
    "EVENT_IDENTIFIER" VARCHAR(255) NOT NULL,
    "META_DATA" BLOB,
    "PAYLOAD" BLOB NOT NULL,
    "PAYLOAD_REVISION" VARCHAR(255),
    "PAYLOAD_TYPE" VARCHAR(255) NOT NULL,
    "TIME_STAMP" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."SNAPSHOT_EVENT_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("AGGREGATE_IDENTIFIER", "SEQUENCE_NUMBER", "TYPE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SNAPSHOT_EVENT_ENTRY;
CREATE MEMORY TABLE "PUBLIC"."TOKEN_ENTRY"(
    "PROCESSOR_NAME" VARCHAR(255) NOT NULL,
    "SEGMENT" INTEGER NOT NULL,
    "OWNER" VARCHAR(255),
    "TIMESTAMP" VARCHAR(255) NOT NULL,
    "TOKEN" BLOB,
    "TOKEN_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TOKEN_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("PROCESSOR_NAME", "SEGMENT");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_ENTRY;
INSERT INTO "PUBLIC"."TOKEN_ENTRY" VALUES
    ('io.axoniq.multitenancy.query', 0, '49420@stefan', '2022-09-26T15:17:14.914Z', NULL, NULL);
ALTER TABLE "PUBLIC"."DOMAIN_EVENT_ENTRY" ADD CONSTRAINT "PUBLIC"."UK8S1F994P4LA2IPB13ME2XQM1W" UNIQUE("AGGREGATE_IDENTIFIER", "SEQUENCE_NUMBER");
ALTER TABLE "PUBLIC"."DOMAIN_EVENT_ENTRY" ADD CONSTRAINT "PUBLIC"."UK_FWE6LSA8BFO6HYAS6UD3M8C7X" UNIQUE("EVENT_IDENTIFIER");
ALTER TABLE "PUBLIC"."DEAD_LETTER_ENTRY" ADD CONSTRAINT "PUBLIC"."UK5O90GYVTPSXM46GIIRSKCL486" UNIQUE("PROCESSING_GROUP", "SEQUENCE_IDENTIFIER", "INDEX");
ALTER TABLE "PUBLIC"."SNAPSHOT_EVENT_ENTRY" ADD CONSTRAINT "PUBLIC"."UK_E1UUCJSEO68GOPMND0VGDL44H" UNIQUE("EVENT_IDENTIFIER");
