### Send a simple Event to the Application

GET http://localhost:8080/event
Content-Type: application/json

### Pause the processor name called "io.axoniq" using Axon Server API.

GET http://localhost:8080/server/pause/io.axoniq
Content-Type: application/json

### Start the processor name called "io.axoniq" using Axon Server API.

GET http://localhost:8080/server/start/io.axoniq
Content-Type: application/json

### Reset the processor name called "io.axoniq" using Axon Server API. Reset means pause, reset token and start.

GET http://localhost:8080/server/reset/io.axoniq
Content-Type: application/json

### Reset the processor name called "io.axoniq" using Axon Framework. Reset means pause, reset token and start.

GET http://localhost:8080/framework/reset/io.axoniq
Content-Type: application/json