package io.axoniq.demo.orderfulfillment.history;

import tools.jackson.core.JacksonException;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;
import io.axoniq.framework.workflow.dsl.api.WorkflowState;
import io.axoniq.framework.workflow.history.api.WorkflowHistory;
import io.axoniq.framework.workflow.history.inmemory.InMemoryWorkflowHistoryRepository;
import io.axoniq.framework.workflow.history.inmemory.MutableWorkflowHistoryRepository;
import io.axoniq.framework.workflow.history.inmemory.WorkflowHistoryProjector;
import io.axoniq.framework.workflow.query.api.WorkflowStateQuery;
import io.axoniq.framework.workflow.query.utils.WorkflowStateQueryMatcher;
import io.axoniq.framework.workflow.runtime.util.MetadataUtils;
import org.axonframework.messaging.core.MessageHandlerInterceptor;
import org.axonframework.messaging.core.MessageHandlerInterceptorChain;
import org.axonframework.messaging.core.MessageStream;
import org.axonframework.messaging.core.Metadata;
import org.axonframework.messaging.core.MessageType;
import org.axonframework.messaging.core.unitofwork.ProcessingContext;
import org.axonframework.messaging.core.unitofwork.UnitOfWorkFactory;
import org.axonframework.messaging.eventhandling.EventMessage;
import org.axonframework.messaging.eventhandling.GenericEventMessage;
import org.axonframework.messaging.eventhandling.conversion.EventConverter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import javax.sql.DataSource;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.function.Function;
import java.util.function.Consumer;

/**
 * Persists workflow events and the latest workflow state for the history console.
 *
 * Each event and its resulting state are stored in a single database transaction.
 * The console reads the stored state and event journal to display workflow progress.
 * Stored events also reconstruct the framework's workflow state so history
 * projection can continue after an application restart.
 */
public class JdbcWorkflowHistoryRepository
        implements MutableWorkflowHistoryRepository, MessageHandlerInterceptor<EventMessage> {

    private final JdbcTemplate jdbc;
    private final TransactionTemplate transactions;
    private final EventConverter converter;
    private final Consumer<String> onCommitted;
    private final ObjectMapper json = JsonMapper.builder().build();
    private final ThreadLocal<Projection> projection = new ThreadLocal<>();
    private UnitOfWorkFactory unitOfWorkFactory;

    public JdbcWorkflowHistoryRepository(DataSource dataSource, EventConverter converter) {
        this(dataSource, converter, id -> { });
    }

    public JdbcWorkflowHistoryRepository(DataSource dataSource, EventConverter converter,
                                         Consumer<String> onCommitted) {
        this.jdbc = new JdbcTemplate(dataSource);
        this.transactions = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        this.converter = converter;
        this.onCommitted = onCommitted;
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS workflow_history (
                    workflow_id VARCHAR(255) PRIMARY KEY,
                    status VARCHAR(40) NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    document CLOB NOT NULL
                )
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS workflow_history_event (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id VARCHAR(255) NOT NULL UNIQUE,
                    workflow_id VARCHAR(255) NOT NULL,
                    event_name VARCHAR(1024) NOT NULL,
                    event_version VARCHAR(255) NOT NULL,
                    occurred_at VARCHAR(40) NOT NULL,
                    payload BLOB NOT NULL,
                    metadata CLOB NOT NULL
                )
                """);
        jdbc.execute("CREATE INDEX IF NOT EXISTS history_event_workflow ON workflow_history_event(workflow_id, sequence)");
    }

    public void initialize(UnitOfWorkFactory unitOfWorkFactory) {
        this.unitOfWorkFactory = unitOfWorkFactory;
    }

    @Override
    public MessageStream<?> interceptOnHandle(EventMessage event, ProcessingContext context,
                                              MessageHandlerInterceptorChain<EventMessage> chain) {
        if (!MetadataUtils.hasWorkflowId().test(event.metadata())) {
            return chain.proceed(event, context);
        }
        return transactions.execute(transaction -> {
            // History can commit before the processor's token. Redelivery must be a no-op.
            if (Boolean.TRUE.equals(jdbc.queryForObject(
                    "SELECT EXISTS(SELECT 1 FROM workflow_history_event WHERE event_id = ?)",
                    Boolean.class, event.identifier()))) {
                return MessageStream.empty();
            }
            projection.set(new Projection(event, context));
            try {
                var result = chain.proceed(event, context);
                // The standard projector performs findById/evolve/save synchronously.
                // Fail explicitly if a future framework version changes that contract.
                if (!result.isCompleted()) {
                    throw new IllegalStateException("History adapter requires a synchronous history projector");
                }
                if (result.error().isPresent()) {
                    throw new IllegalStateException("History projection failed", result.error().get());
                }
                return result;
            } finally {
                projection.remove();
            }
        });
    }

    @Override
    public void save(WorkflowHistory history) {
        var active = projection.get();
        if (active == null) {
            throw new IllegalStateException("Configure this repository as the history processor interceptor too");
        }
        var event = active.event();
        if (!history.workflowId().equals(MetadataUtils.getWorkflowId(event.metadata()))) {
            throw new IllegalArgumentException("History and event workflow IDs differ");
        }
        jdbc.update("""
                INSERT INTO workflow_history_event
                    (event_id, workflow_id, event_name, event_version, occurred_at, payload, metadata)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, event.identifier(), history.workflowId(), event.type().qualifiedName().toString(),
                    event.type().version(), event.timestamp().toString(), event.payloadAs(byte[].class),
                    write(event.metadata()));
        jdbc.update("""
                MERGE INTO workflow_history (workflow_id, status, updated_at, document)
                KEY (workflow_id) VALUES (?, ?, ?, ?)
                """, history.workflowId(), history.state().workflowStatus().name(),
                    OffsetDateTime.ofInstant(event.timestamp(), ZoneOffset.UTC), write(document(history.state(), event)));
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCommit() {
                onCommitted.accept(history.workflowId());
            }
        });
    }

    @Override
    public CompletableFuture<Optional<WorkflowHistory>> findById(String workflowId) {
        return withContext(context -> restore(workflowId, context));
    }

    @Override
    public CompletableFuture<List<WorkflowHistory>> findAll(WorkflowStateQuery query) {
        // For this small demo, evaluate the framework's complete query semantics in Java.
        // The UI uses the indexed SQL list below and does not replay every workflow.
        return withContext(context -> jdbc.queryForList("SELECT workflow_id FROM workflow_history", String.class)
                .stream().map(id -> restore(id, context)).flatMap(Optional::stream)
                .filter(history -> WorkflowStateQueryMatcher.matches(query, history.state())).toList());
    }

    private Optional<WorkflowHistory> restore(String workflowId, ProcessingContext context) {
        var memory = new InMemoryWorkflowHistoryRepository();
        var projector = new WorkflowHistoryProjector(memory);
        jdbc.query("SELECT * FROM workflow_history_event WHERE workflow_id = ? ORDER BY sequence",
                   (org.springframework.jdbc.core.RowCallbackHandler) row -> projector.handle(readEvent(row), context),
                   workflowId);
        return memory.findById(workflowId).join();
    }

    private <T> CompletableFuture<T> withContext(Function<ProcessingContext, T> operation) {
        var active = projection.get();
        if (active != null) {
            return CompletableFuture.completedFuture(operation.apply(active.context()));
        }
        if (unitOfWorkFactory == null) {
            return CompletableFuture.failedFuture(new IllegalStateException("History repository is not initialized"));
        }
        return unitOfWorkFactory.create().executeWithResult(
                context -> CompletableFuture.completedFuture(operation.apply(context)));
    }

    @Override
    public void clear() {
        transactions.executeWithoutResult(transaction -> {
            jdbc.update("DELETE FROM workflow_history_event");
            jdbc.update("DELETE FROM workflow_history");
        });
    }

    public Map<String, Object> list(String search, String status, int limit, int offset) {
        var pattern = "%" + search.toLowerCase(java.util.Locale.ROOT)
                .replace("!", "!!").replace("%", "!%").replace("_", "!_") + "%";
        var where = " WHERE LOWER(workflow_id) LIKE ? ESCAPE '!' AND (? = '' OR status = ?)";
        var items = jdbc.query("SELECT document FROM workflow_history" + where
                                      + " ORDER BY updated_at DESC, workflow_id LIMIT ? OFFSET ?",
                              (row, index) -> read(row.getString(1)), pattern, status, status, limit, offset);
        var total = jdbc.queryForObject("SELECT COUNT(*) FROM workflow_history" + where,
                                       Long.class, pattern, status, status);
        return Map.of("items", items, "total", total, "limit", limit, "offset", offset, "storage", "H2 file");
    }

    public Optional<Object> detail(String workflowId) {
        return jdbc.query("SELECT document FROM workflow_history WHERE workflow_id = ?",
                          (row, index) -> read(row.getString(1)), workflowId).stream().findFirst();
    }

    public List<Map<String, Object>> timeline(String workflowId, long after, int limit) {
        return jdbc.query("""
                SELECT * FROM workflow_history_event
                WHERE workflow_id = ? AND sequence > ? ORDER BY sequence LIMIT ?
                """, (row, index) -> {
            var event = readEvent(row);
            Map<String, Object> item = new LinkedHashMap<>();
            item.put("sequence", row.getLong("sequence"));
            item.put("eventId", event.identifier());
            item.put("type", event.type().qualifiedName().toString());
            item.put("version", event.type().version());
            item.put("timestamp", event.timestamp().toString());
            item.put("step", MetadataUtils.getStepStatus(event.metadata()).isPresent()
                    ? MetadataUtils.getStepName(event.metadata()) : null);
            item.put("status", MetadataUtils.getStepStatus(event.metadata()).map(Enum::name)
                    .orElseGet(() -> MetadataUtils.getWorkflowStatus(event.metadata()).map(Enum::name).orElse("EVENT")));
            item.put("payload", read(new String(row.getBytes("payload"), java.nio.charset.StandardCharsets.UTF_8)));
            item.put("metadata", event.metadata());
            return item;
        }, workflowId, after, limit);
    }

    private Map<String, Object> document(WorkflowState state, EventMessage event) {
        Map<String, Object> document = new LinkedHashMap<>();
        document.put("workflowId", state.workflowId());
        document.put("definition", state.workflowDefinitionId().qualifiedName().toString());
        document.put("version", state.workflowDefinitionId().version());
        document.put("status", state.workflowStatus().name());
        document.put("updatedAt", event.timestamp().toString());
        document.put("startedAt", jdbc.queryForObject("""
                SELECT occurred_at FROM workflow_history_event WHERE workflow_id = ? ORDER BY sequence LIMIT 1
                """, String.class, state.workflowId()));
        document.put("payload", state.payload());
        document.put("versionMigrations", state.versionMigrations());
        document.put("steps", state.workflowStepNames().stream().map(name -> {
            var step = state.getStep(name);
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("name", name);
            entry.put("status", step.status().name());
            entry.put("timestamp", step.timestamp().toString());
            entry.put("result", step.result());
            entry.put("error", step.error() == null ? null : step.error().toString());
            return entry;
        }).toList());
        return document;
    }

    private EventMessage readEvent(ResultSet row) throws SQLException {
        try {
            Map<String, String> metadata = json.readValue(row.getString("metadata"), new TypeReference<>() { });
            return new GenericEventMessage(row.getString("event_id"),
                    new MessageType(row.getString("event_name"), row.getString("event_version")),
                    // Materialize JSON first: payloadAs(Object.class) otherwise returns the
                    // byte[] unchanged, leaving reconstructed step results as binary data.
                    read(new String(row.getBytes("payload"), java.nio.charset.StandardCharsets.UTF_8)),
                    Metadata.from(metadata), Instant.parse(row.getString("occurred_at")))
                    .withConverter(converter);
        } catch (JacksonException e) {
            throw new IllegalStateException("Cannot read stored event metadata", e);
        }
    }

    private String write(Object value) {
        try {
            return json.writeValueAsString(value);
        } catch (JacksonException e) {
            throw new IllegalStateException("Cannot encode workflow history", e);
        }
    }

    private Object read(String value) {
        try {
            return json.readValue(value, Object.class);
        } catch (JacksonException e) {
            throw new IllegalStateException("Cannot decode workflow history", e);
        }
    }

    private record Projection(EventMessage event, ProcessingContext context) { }
}
